config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :meals
  # resources :customer_meals
  match 'like', to: 'customer_meals#like', via: :post
  match 'unlike', to: 'customer_meals#unlike', via: :delete
  
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  root 'welcome#index'
  
  get 'mymealplan', to: 'mealplan#show', as: 'mymealplan'
  post 'mymealplan/update', to: 'mealplan#update', as: 'update_mymealplan'

  resources :addresses
  
  #admin controller
  get 'admin/index', to: 'admin#index', as: 'admin' 
  
   #admin invoices
  get '/admin/invoices', to: 'admin#invoices', as: 'admin_invoices'
  get '/admin/generate_invoices/:date', to: 'admin#generate_invoices', as: 'admin_generate_invoices'
  get '/admin/delete_invoice/:id', to: 'admin#delete_invoice', as: 'admin_delete_invoice'
  get '/admin/charge_invoice/:invoiceid', to: 'admin#charge_invoice', as: 'admin_charge_invoice'
  
  #admin mealplans
  get 'admin/mealplans', to: 'admin#mealplans', as: 'admin_mealplans'
  get 'admin/generate_n_ramdom_mealplans/:n', to: 'admin#generate_n_ramdom_mealplans', as: 'admin_generate_n_ramdom_mealplans'
  

end

app/models/mealplan.rb
class Mealplan < ApplicationRecord
  belongs_to :customer
  has_many :addresses, as: :addressable
  
  # def first_line
  #   Mealplan.address.street
  # end
  
# this is more for testing purposes or if you want for each customer to have a 
# default meal plan. You can generate one any time someone creates an account.
  def self.create_default(customer)
    @mealplan = Mealplan.new
    @mealplan.customer = customer
    @mealplan.monday = 0
    @mealplan.tuesday = 0
    @mealplan.wednesday = 0
    @mealplan.thursday = 0
    @mealplan.friday = 0
    @mealplan.saturday = 0
    @mealplan.sunday = 0
    @mealplan.state = "Active"
    @mealplan.save
    return @mealplan
  end

  # def self.get_plan(customer)
  #   if customer.mealplans.size == 0 then create_default(customer) end
  #   @plan = customer.mealplans.first
  #   return @plan
  # end

  def self.save_plan(params, current_user)
    #"Params " + params["mealplan"]["title"].to_s)
    @mealplan = params["mealplan"]
    @plan = Mealplan.new
    @plan.customer = current_user
    @plan.title = @mealplan["title"]
    @plan.sunday = @mealplan["sunday"]
    @plan.monday = @mealplan["monday"]
    @plan.tuesday = @mealplan["tuesday"]
    @plan.wednesday = @mealplan["wednesday"]
    @plan.thursday = @mealplan["thursday"]
    @plan.friday = @mealplan["friday"]
    @plan.saturday = @mealplan["saturday"]
    @plan.status = "Active"    
    @plan.save
    #Log.info(@plan.inspect)
  end

  def self.update_plan(params)
    #"Params " + params["mealplan"]["title"].to_s)
    @params = params
    @mealplan = Mealplan.find_by_id(@params["mealplan"]["id"])
    # if @plan != nil then 
	   # @plan.title = @mealplan["title"]
	    @mealplan.monday = @params["mealplan"]["monday"]
	    @mealplan.tuesday = @params["mealplan"]["tuesday"]
	    @mealplan.wednesday = @params["mealplan"]["wednesday"]
	    @mealplan.thursday = @params["mealplan"]["thursday"]
	    @mealplan.friday = @params["mealplan"]["friday"]
	    @mealplan.saturday = @params["mealplan"]["saturday"]
	    @mealplan.sunday = @params["mealplan"]["sunday"]
	    if  @params["monday_address"]
	      @mealplan.monday_address = @params["monday_address"]["address_id"].to_i
	    end
	    if  @params["tuesday_address"]
	      @mealplan.tuesday_address = @params["tuesday_address"]["address_id"].to_i
	    end
	    if  @params["wednesday_address"]
	      @mealplan.wednesday_address = @params["wednesday_address"]["address_id"].to_i
	    end
	    if  @params["thursday_address"]
	      @mealplan.thursday_address = @params["thursday_address"]["address_id"].to_i
	    end
	    if  @params["friday_address"]
	      @mealplan.friday_address = @params["friday_address"]["address_id"].to_i
	    end
	    if  @params["saturday_address"]
	      @mealplan.saturday_address = @params["saturday_address"]["address_id"].to_i
	    end
	    if  @params["sunday_address"]
	      @mealplan.sunday_address = @params["sunday_address"]["address_id"].to_i
	    end
	    @mealplan.state = "Active"    
	    @mealplan.save
	    
    # end
    #Log.info(@plan.inspect)
  end

  # def self.update_plan_errors(params)
  #   @errors = ""
  #   @mealplan = params["mealplan"]
  #   @title = @mealplan["title"]
  #   @monday = @mealplan["monday"]
  #   @tuesday = @mealplan["tuesday"]
  #   @wednesday = @mealplan["wednesday"]
  #   @thursday = @mealplan["thursday"]
  #   @friday = @mealplan["friday"]
  #   @saturday = @mealplan["saturday"]
  #   @sunday = @mealplan["sunday"]
  #   if @title == "" then @errors += "Title is empty." end
  #   if @monday == "" then @errors += "Monday is empty." end
  #   if @tuesday == "" then @errors += "Tuesday is empty." end
  #   if @wednesday == "" then @errors += "Wednesday is empty." end
  #   if @thursday == "" then @errors += "Thursday is empty." end
  #   if @friday == "" then @errors += "Friday is empty." end
  #   if @saturday == "" then @errors += "Saturday is empty." end
  #   if @sunday == "" then @errors += "Sunday is empty." end
  #   #add additional errors
  #   return @errors
  # end
  
  # def self.save_plan_errors(params)#checks common errors so the plan doesn't get saved badly
  #   @errors = ""
  #   @mealplan = params["mealplan"]
  #   @title = @mealplan["title"]
  #   @monday = @mealplan["monday"]
  #   @tuesday = @mealplan["tuesday"]
  #   @wednesday = @mealplan["wednesday"]
  #   @thursday = @mealplan["thursday"]
  #   @friday = @mealplan["friday"]
  #   @saturday = @mealplan["saturday"]
  #   @sunday = @mealplan["sunday"]
  #   if @title == "" then @errors += "Title is empty." end
  #   if @monday == "" then @errors += "Monday is empty." end
  #   if @tuesday == "" then @errors += "Tuesday is empty." end
  #   if @wednesday == "" then @errors += "Wednesday is empty." end
  #   if @thursday == "" then @errors += "Thursday is empty." end
  #   if @friday == "" then @errors += "Friday is empty." end
  #   if @saturday == "" then @errors += "Saturday is empty." end
  #   if @sunday == "" then @errors += "Sunday is empty." end
  #   #add additional errors
  #   return @errors
  # end


  # def self.get_mealplans_with_orders_by_wday(wday)#you give zero and you get all the customers who have meals sunday
  #   if wday == 0 then @mealplans = Mealplan.where("sunday > 0") end
  #   if wday == 1 then @mealplans = Mealplan.where("monday > 0") end
  #   if wday == 2 then @mealplans = Mealplan.where("tuesday > 0") end
  #   if wday == 3 then @mealplans = Mealplan.where("wednesday > 0") end
  #   if wday == 4 then @mealplanrs = Mealplan.where("thursday > 0") end
  #   if wday == 5 then @mealplans = Mealplan.where("friday > 0") end
  #   if wday == 6 then @mealplans = Mealplan.where("saturday > 0") end
  #   return @mealplans
  # end

  # def self.get_value_by_wday(mealplan, wday)#you retrieve how many meals a plan does have in any week day
  #   @value = 0
  #   if wday == 0 then @value = mealplan.sunday end
  #   if wday == 1 then @value = mealplan.monday end
  #   if wday == 2 then @value = mealplan.tuesday end
  #   if wday == 3 then @value = mealplan.wednesday end
  #   if wday == 4 then @value = mealplan.thursday end
  #   if wday == 5 then @value = mealplan.friday end
  #   if wday == 6 then @value = mealplan.saturday end
  #   return @value
  # end

  def self.generate_n_ramdom_mealplans(n)
    #destroy all customers and mealplans
    # Mealplan.all.destroy_all
    Customer.all.destroy_all
    #generate 100 customers, each with a meal plan and a random number of meals per day    
    for @i in (1..n.to_i) do
      @customer = Customer.new(email: @i.to_s + "@mail.com", password: "password")
      @customer.save
      @mealplan = Mealplan.create_default(@customer)
      @mealplan.monday = rand(10)
      @mealplan.tuesday = rand(10)
      @mealplan.wednesday = rand(10)
      @mealplan.thursday = rand(10)
      @mealplan.friday = rand(10)
      @mealplan.saturday = rand(10)
      @mealplan.sunday = rand(10)
      @mealplan.lat = 52.204266 + rand(-0.045..0.045)
      @mealplan.long = 0.119907 + rand(-0.045..0.045)
      @mealplan.state = "Active"
      @mealplan.save
    end
  end
end

app/controllers/mealplan_controller.rb
class MealplanController < ApplicationController
  before_action :authenticate_customer!
  
  def show 
    Mealplan.create_default(current_customer) unless current_customer.mealplan != nil
    #!!!!!! Why can't I pass this @plan variable to the show view, I had to it directly in views
    # @plan = current_customer.mealplan
    respond_to do |wants|
      wants.html { redirect_to root_path }
      wants.js
    end
  end

  def update
    Mealplan.update_plan(params)
    @plan = Mealplan.find_by_id(current_customer)
    respond_to do |wants|
      wants.html { redirect_to root_path }
      wants.js {  flash.now[:notice] = "Changes saved." }
    end
  end
end



  

app/helpers/mealplan_helper.rb
module MealplanHelper
end

app/views/mealplan/_show.html.erb
<% if current_customer %>
  <div class="card" id="settings">
    <h4 class="settings_heading">Order Settings</h4>
    <%# debugger %>
    <%= form_for current_customer.mealplan, remote: true, html: {:class => 'form-horizontal'}, method: 'POST', url: :update_mymealplan do |f| %>
      <%= f.hidden_field :id, :value => current_customer.mealplan.id %>
      <div class="form-group">
        <%= f.label :mon, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :monday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.monday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.monday_address)[0] != nil) %>
            <%= select("monday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, {:selected => Address.where(:id => current_customer.mealplan.monday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.monday_address)[0] == nil %>
            <%= select("monday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }, html: { id: "testing_123"}) %>
          <% else %>
            Address needed
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :tue, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :tuesday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.tuesday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.tuesday_address)[0] != nil)%>
            <%= select("tuesday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.tuesday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.tuesday_address)[0] == nil %>
            <%= select("tuesday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :wed, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :wednesday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.wednesday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.wednesday_address)[0] != nil)%>
            <%= select("wednesday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.wednesday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.wednesday_address)[0] == nil %>
            <%= select("wednesday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>     
        </div>
      </div>
      <div class="form-group">
        <%= f.label :thu, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :thursday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.thursday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.thursday_address)[0] != nil)%>
            <%= select("thursday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.thursday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.thursday_address)[0] == nil %>
            <%= select("thursday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>   
        </div>
      </div>
      <div class="form-group">
        <%= f.label :fri, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :friday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.friday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.friday_address)[0] != nil)%>
            <%= select("friday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.friday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.friday_address)[0] == nil %>
            <%= select("friday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>     
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sat, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :saturday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.saturday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.saturday_address)[0] != nil)%>
            <%= select("saturday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.saturday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.saturday_address)[0] == nil %>
            <%= select("saturday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>  
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sun, :class => 'control-label col-sm-2' %>
        <div class="col-sm-1">
          <%= f.select :sunday, [['0 ', 0], ['1 ', 1], ['2 ', 2], ['3 ', 3], ['4 ', 4], ['5 ', 5], ['6 ', 6], ['7 ', 7], ['8 ', 8], ['9 ', 9], ['10 ', 10]], :selected => current_customer.mealplan.sunday %>
        </div>
        <div>
          <% if Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && (Address.where(:id => current_customer.mealplan.sunday_address)[0] != nil)%>
            <%= select("sunday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :selected => Address.where(:id => current_customer.mealplan.sunday_address)[0].id } ) %>
          <% elsif Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").count > 0 && Address.where(:id => current_customer.mealplan.sunday_address)[0] == nil %>
            <%= select("sunday_address", "address_id", Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all.collect {|p| [p.street.truncate(16), p.id] }, { :prompt => "Select address" }) %>
          <% else %>
            Address needed
          <% end %>      
        </div>
      </div>      
      <% if Address.where(:addressable_id => current_customer.mealplan.id ).count != 0 %>
        <%= link_to "My Addresses", addresses_path, class: "btn btn-md btn-default", id: "add_edit_address_btn", remote: true %>
        <%= f.submit "Save changes", class: 'btn btn-primary settings_button', id: "save_settings_btn" %>
      <% else %>
        <%= link_to "Add Address", new_address_path, class: "btn btn-md btn-success add_address_btn", id: "add_address_btn", remote: true %>
      <% end %>
    <% end %>
  </div>
<% end %>

<script>
$(function(){
  $("#monday_address_address_id, #mealplan_monday, #tuesday_address_address_id, #mealplan_tuesday, #wednesday_address_address_id, #mealplan_wednesday, #thursday_address_address_id, #mealplan_thursday, #friday_address_address_id, #mealplan_friday, #saturday_address_address_id, #mealplan_saturday, #sunday_address_address_id, #mealplan_sunday").change(function () {
        $('#add_edit_address_btn').css("display", "none");
        $('#save_settings_btn').css("display", "inline-block");
    });
});
</script>

app/views/mealplan/bill_customers.html.erb
<%= for @mealplan in @mealplans do%>
  <%= @mealplan.id %>&nbsp;<%= @mealplan.sunday %></br>
<% end %>

app/views/mealplan/edit.html.erb
<div class="container">
<h1>Edit plan</h1>
<%= form_for @plan, :html => {:class => 'form-horizontal'}, :method => 'POST', url: :update_mealplan do |f| %>
   <%= f.hidden_field :id, :value => @plan.id %>
 </div>
 <div class="form-group">
  <%= f.label :monday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :monday, value: @plan.monday, :class => 'form-control' %> 
  </div>
 </div>
 <div class="form-group">
  <%= f.label :tuesday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :tuesday, value: @plan.tuesday, :class => 'form-control' %> 
  </div>
 </div>
 <div class="form-group">
  <%= f.label :wednesday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :wednesday, value: @plan.wednesday, :class => 'form-control' %> 
  </div>
 </div>
 <div class="form-group">
  <%= f.label :thursday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :thursday, value: @plan.thursday, :class => 'form-control' %> 
  </div>
 </div>
 <div class="form-group">
  <%= f.label :friday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :friday, value: @plan.friday, :class => 'form-control' %> 
  </div>
 </div>
 <div class="form-group">
  <%= f.label :saturday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :saturday, value: @plan.saturday, :class => 'form-control' %> 
  </div>
 </div>
  <div class="form-group">
  <%= f.label :sunday, :class => 'control-label col-sm-2' %>
  <div class="col-sm-1">
    <%= f.text_field :sunday, value: @plan.sunday, :class => 'form-control' %> 
  </div>
 </div>
  <%= f.submit "Update", :class => 'btn btn-primary' %>&nbsp;&nbsp;<%= link_to "All plans", mealplans_path, :class => 'btn btn-default'%>
 <% end %>
</div>

app/views/mealplan/index.html.erb
<div class="container">
  <h1>Plans</h1>
  <p><%= @mealplans.size %> plans.</p>      
</div>
<% if @mealplans.size > 0 then %>
 <div class="container">
        
  <table class="table table-striped">
    <thead>
      <tr>
        <!--<th>Title</th>-->
        <th>Monday</th>
        <th>Tuesday</th>
	<th>Wednesday</th>
	<th>Thursday</th>
	<th>Friday</th>
	<th>Saturday</th>
	<th>Sunday</th>
	<th>Status</th>
	<th>Operations</th>
      </tr>
    </thead>
    <tbody>
     <% for @mealplan in @mealplans do %>
      <tr>
        <!--<td><%#=@mealplan.title%></td>-->
        <td><%=@mealplan.monday%></td>
        <td><%=@mealplan.tuesday%></td>
	      <td><%=@mealplan.wednesday%></td>
        <td><%=@mealplan.thursday%></td>
        <td><%=@mealplan.friday%></td>
	      <td><%=@mealplan.saturday%></td>
        <td><%=@mealplan.sunday%></td>
        <td><%=@mealplan.state%></td>
        <td><%= link_to "Edit plan", edit_mealplan_path(@mealplan.id), :class => 'btn btn-primary btn-sm'%>&nbsp;
	<%= link_to "Delete plan", delete_mealplan_path(@mealplan.id), :class => 'btn btn-danger btn-sm'%></td>
      </tr>
     <% end %>
    </tbody>
  </table>
</div>
<% end %>
<div class="clear"></div>
<div class="container">
  <%= link_to "Add plan", new_mealplan_path, :class => 'btn btn-primary'%>
</div>
<div class="clear"></div>

app/views/mealplan/show.js.erb
$('#my_addresses_list').remove();
$('#settings').remove();
$('#enter_address_form').remove();
$('#append_to_index').append('<%= j render("show") %>');

app/views/mealplan/update.js.erb
$('#my_addresses_list').remove();
$('#settings').remove();
$('#enter_address_form').remove();
$('#append_to_index').append('<%= j render("show") %>');

$("#bootstrap-flash").html("<%= j (bootstrap_flash) %>");
$(".alert").hide();
$(".alert").slideDown(350);
$(".alert").delay(2500).fadeTo(200, 0).slideUp(350, function(){
  $(this).remove(); 
});