config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :meals
  # resources :customer_meals
  match 'like', to: 'customer_meals#like', via: :post
  match 'unlike', to: 'customer_meals#unlike', via: :delete
  
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  root 'welcome#index'
  
  get 'mymealplan', to: 'mealplan#show', as: 'mymealplan'
  post 'mymealplan/update', to: 'mealplan#update', as: 'update_mymealplan'

  resources :addresses
  
  #admin controller
  get 'admin/index', to: 'admin#index', as: 'admin' 
  
   #admin invoices
  get '/admin/invoices', to: 'admin#invoices', as: 'admin_invoices'
  get '/admin/generate_invoices/:date', to: 'admin#generate_invoices', as: 'admin_generate_invoices'
  get '/admin/delete_invoice/:id', to: 'admin#delete_invoice', as: 'admin_delete_invoice'
  get '/admin/charge_invoice/:invoiceid', to: 'admin#charge_invoice', as: 'admin_charge_invoice'
  
  #admin mealplans
  get 'admin/mealplans', to: 'admin#mealplans', as: 'admin_mealplans'
  get 'admin/generate_n_ramdom_mealplans/:n', to: 'admin#generate_n_ramdom_mealplans', as: 'admin_generate_n_ramdom_mealplans'
  

end

app/views/admin/index.html.erb
<div class="container" style="width:50%;">
  <h2>Admin</h2>
  <table class="table table-striped">
    
    <tbody>
      <tr>
        <td><%= link_to "Meal plans", admin_mealplans_path%>&nbsp;<span class="badge"><%= @no_mealplans %></span></td>
      </tr>
      <tr>
         <td>Customers<%#= link_to "Customers", admin_customers_path%>&nbsp;<span class="badge"><%=@no_customers%></span></td>
      </tr>
      <tr>
         <td>Chefs<%#= link_to "Chefs", admin_chefs_path%>&nbsp;<span class="badge"><%=@no_chefs%></span></td>
      </tr>
      <tr>
         <td><%= link_to "Invoices", admin_invoices_path%>&nbsp;<span class="badge"><%=@no_invoices%></span></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/invoices.html.erb
<div class="container">
  <%= link_to "Admin", admin_path, :class => 'btn btn-default'%> </br>
  <h1>Invoices admin</h1>
  <%= @no_invoices %>&nbsp;invoices. </br></br>
  Pick a date:
  <input id="date" type="text" value="<%=@date%>" size="9"/>
  <div id="generate_invoices" class="btn btn-primary" style="width:200px;">Generate invoices</div>
  </br>
 <%if @invoices.size > 0 then %>
   <div class="container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>No.</th>
          <th>Customer email</th>
          <th>No. meals</th>
          <th>Prediction range</th>
          <th>Due Date</th>
        	<th>Paid</th>
        	<th>Payment token</th>
        	<th>Operations</th>
        </tr>
      </thead>
      <tbody>
        <% @counter = 0 %>
        <%# for @invoice in @invoices do%>
        <% for @invoice in Invoice.all do %>
          <tr>
            <td><% @counter = @counter + 1%> <%=@counter%>
            </td>
            <td><%=@invoice.customer.email%></td>
            <td><%= @invoice.no_meals %></td>
            <td><%= @invoice.prediction_range %></td>
            <td><div data-toggle="tooltip" data-placement="top" title="<%= @invoice.due_date.to_s%>" style="display:inline;"><%= @invoice.due_date.strftime("%d %b %Y")%></div></td>
            <td><%= @invoice.paid %></td>
          	<td><%= @invoice.payment_token %></td>
          	<td><%= link_to "Charge", admin_charge_invoice_path(@invoice.id), :class => 'btn btn-primary btn-sm'%>&nbsp;<%= link_to "Delete", admin_delete_invoice_path(@invoice.id), :class => 'btn btn-danger btn-sm'%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 <% end %>
</div>

<script>
  $("#generate_invoices").click(function(){
    var current_date = String($("#date").val());
    window.location = "/admin/generate_invoices/" + current_date;
  });
</script>

app/views/admin/mealplans.html.erb
<div class="container">
  <%= link_to "Admin", admin_path, :class => 'btn btn-default'%> </br>
  <h1>Meal plans admin</h1>
  <%= @no_mealplans %>&nbsp;mealplans. </br>
  <%= link_to "Generate 100 random mealplans", admin_generate_n_ramdom_mealplans_path(100) %> </br>
</div>