config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :meals
  # resources :customer_meals
  match 'like', to: 'customer_meals#like', via: :post
  match 'unlike', to: 'customer_meals#unlike', via: :delete
  
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  root 'welcome#index'
  
  get 'mymealplan', to: 'mealplan#show', as: 'mymealplan'
  post 'mymealplan/update', to: 'mealplan#update', as: 'update_mymealplan'

  resources :addresses
  
  #admin controller
  get 'admin/index', to: 'admin#index', as: 'admin' 
  
   #admin invoices
  get '/admin/invoices', to: 'admin#invoices', as: 'admin_invoices'
  get '/admin/generate_invoices/:date', to: 'admin#generate_invoices', as: 'admin_generate_invoices'
  get '/admin/delete_invoice/:id', to: 'admin#delete_invoice', as: 'admin_delete_invoice'
  get '/admin/charge_invoice/:invoiceid', to: 'admin#charge_invoice', as: 'admin_charge_invoice'
  
  #admin mealplans
  get 'admin/mealplans', to: 'admin#mealplans', as: 'admin_mealplans'
  get 'admin/generate_n_ramdom_mealplans/:n', to: 'admin#generate_n_ramdom_mealplans', as: 'admin_generate_n_ramdom_mealplans'
  

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
    @addresses =  Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all
  end
  
  def new
    @address = Address.new
  end
  
  def edit
    @address = Address.find_by_id(params[:id])
  end
  
  def create
    @address = Address.new(address_params)
    @address.addressable = current_customer.mealplan
    respond_to do |wants|
      if @address.save
        wants.html { redirect_to addresses_path }
        wants.js {  flash.now[:notice] = "Succesfully added address." }
      else
        # wants.html { redirect_to addresses_path }
        wants.js {  flash.now[:danger] = "That was a bank address!" }
        # flash[:danger] = "That was a bank address!"
      end
      @addresses =  Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all
    end
  end
  
  def update
    Address.update_address(params)
    @addresses =  Address.where(:addressable_id => current_customer.mealplan.id, :addressable_type => "Mealplan").all
    respond_to do |wants|
      wants.html { redirect_to addresses_path }
      wants.js {  flash.now[:notice] = "Succesfully updated address." }
    end
  end
  
  def destroy
    @address = Address.destroy(params[:id])
    respond_to do |wants|
      wants.html { redirect_to addresses_path }
      wants.js {  flash.now[:danger] = "Succesfully deleted address." }
    end
  end
  
  private
  def address_params
    params.require(:address).permit(:street, :city, :postcode, :details, :phone)
  end
end

app/views/addresses/_edit.html.erb
<% if @address.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@address.errors.count, "error") %> prohibited your this from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>
<span id="edit_address">  
  <div class="card">
    <%= form_for @address, remote: true, html: { multipart: true, class: "form-horizontal meal" } do |f| %>
      <h4 class="delivery_address_heading">Edit Address</h4>
      <div class="form-group" id="street_address">
        <%= f.text_field :street, class: 'form-control col-md-12', placeholder: "Address line 1" %>
      </div>
      <div class="form-group" id="street_address">
        <%= f.text_field :city, class: 'form-control col-md-6', placeholder: "City or Town" %>
      </div>
      <div class="form-group" id="postcode_address">
        <%= f.text_field :postcode, class: 'form-control', placeholder: "Postcode" %>
      </div>
      <div class="form-group" id="details_address">
        <%= f.text_area :details, class: 'form-control details_address', placeholder: "Extra info: where to leave your food so we keep on time, and difficult to find entrances." %>
      </div>
      <div class="form-group" id="phone_details">
        <%= f.text_field :phone, class: 'form-control', placeholder: "Phone number" %>
      </div>
      
      <div class="form-group" id="div_for_address_btn">
          <%= link_to "Back", addresses_path, class: "btn btn-default  cancel_address", id: "cancel_address", remote: true %>
          <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</span>

app/views/addresses/_index.html.erb
<div class="card" id="my_addresses_list">
  <h4 class="delivery_address_heading saved_addresses_heading">My Addresses</h4>
  <div class="addresses_div">
    <% if @addresses != nil %>
      <% @addresses.each do |address| %>
        <div class="address_item" id="address_id_<% address.id %>" >
          <span><%= address.street.truncate(18) %></span>
          <%= link_to "Edit", edit_address_path(address.id), class: "btn-primary btn-sm edit-btn", remote: true %>
          <%= link_to "Delete", address_path(address.id), class: "btn btn-xs btn-danger delete-btn delete-btn2", method: :delete, remote: true %>          
        </div></br>
      <% end %>
    <% end %>
  </div>
  <div class="form-group" id="div_for_address_btn">
    <%= link_to "Settings", mymealplan_path, class: "btn btn-default cancel_address", id: "cancel_address2", remote: true %>
    <%= link_to "Add address", new_address_path, class: "btn btn-success add_address_btn", id: "add_address_btn2", remote: true %>
  </div>
</div>

app/views/addresses/_new.html.erb
<% if @address.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@address.errors.count, "error") %> prohibited your this from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>
<span id="enter_address_form"> 
  <div class="card">
    <%= form_for @address, remote: true, html: { multipart: true, class: "form-horizontal meal" } do |f| %>
      <h4 class="delivery_address_heading">Add Address</h4>
      <div class="form-group" id="street_address">
        <%= f.text_field :street, class: 'form-control col-md-12', placeholder: "Address line 1" %>
      </div>
      <div class="form-group" id="street_address">
        <%= f.text_field :city, class: 'form-control col-md-6', placeholder: "City or Town" %>
      </div>
      <div class="form-group" id="postcode_address">
        <%= f.text_field :postcode, class: 'form-control', placeholder: "Postcode" %>
      </div>
      <div class="form-group" id="details_address">
        <%= f.text_area :details, class: 'form-control details_address', placeholder: "Extra info: where to leave your food so we keep on time, and difficult to find entrances." %>
      </div>
      <div class="form-group" id="phone_details">
        <%= f.text_field :phone, class: 'form-control', placeholder: "Phone number" %>
      </div>
      
      <div class="form-group" id="div_for_address_btn">
        
        <% if Address.where(:addressable_id => current_customer.mealplan.id ).count != 0 %>
          <%= link_to "Back", addresses_path, class: "btn btn-default cancel_address", id: "cancel_address", remote: true %>
        <% else %>
          <%= link_to "Back", root_path, class: "btn btn-default", id: "cancel_address", remote: true %>
        <% end %>
          <%= f.submit "Save", :class => 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</span>

app/views/addresses/create.js.erb
$('#enter_address_form').remove();
$('#append_to_index').append('<%= j render('addresses/index')%>');

$("#bootstrap-flash").html("<%= j (bootstrap_flash) %>");
$(".alert").hide();
$(".alert").slideDown(350);
$(".alert").delay(2500).fadeTo(200, 0).slideUp(350, function(){
  $(this).remove(); 
});

app/views/addresses/destroy.js.erb
$('#address_id_<% @address.id %>').remove();

app/views/addresses/edit.js.erb
$('#my_addresses_list').remove();
$('#append_to_index').append('<%= j render("edit") %>');

app/views/addresses/index.js.erb
$('#enter_address_form').remove();
$('#settings').remove();
$('#edit_address').remove();
$('#append_to_index').append('<%= j render("index") %>');

app/views/addresses/new.js.erb
$('#settings').remove();
$('#my_addresses_list').remove();
$('#append_to_index').append('<%= j render("new") %>');

app/views/addresses/update.js.erb
$("#edit_address").remove();
$("#append_to_index").append('<%= j render("addresses/index") %>');

$("#bootstrap-flash").html("<%= j (bootstrap_flash) %>");
$(".alert").hide();
$(".alert").slideDown(350);
$(".alert").delay(2500).fadeTo(200, 0).slideUp(350, function(){
  $(this).remove(); 
});