config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :meals
  # resources :customer_meals
  match 'like', to: 'customer_meals#like', via: :post
  match 'unlike', to: 'customer_meals#unlike', via: :delete
  
  devise_for :chefs, :controllers => { :registrations => "chef/registrations" }
  root 'welcome#index'
  
  get 'mymealplan', to: 'mealplan#show', as: 'mymealplan'
  post 'mymealplan/update', to: 'mealplan#update', as: 'update_mymealplan'

  resources :addresses
  
  #admin controller
  get 'admin/index', to: 'admin#index', as: 'admin' 
  
   #admin invoices
  get '/admin/invoices', to: 'admin#invoices', as: 'admin_invoices'
  get '/admin/generate_invoices/:date', to: 'admin#generate_invoices', as: 'admin_generate_invoices'
  get '/admin/delete_invoice/:id', to: 'admin#delete_invoice', as: 'admin_delete_invoice'
  get '/admin/charge_invoice/:invoiceid', to: 'admin#charge_invoice', as: 'admin_charge_invoice'
  
  #admin mealplans
  get 'admin/mealplans', to: 'admin#mealplans', as: 'admin_mealplans'
  get 'admin/generate_n_ramdom_mealplans/:n', to: 'admin#generate_n_ramdom_mealplans', as: 'admin_generate_n_ramdom_mealplans'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lunchise" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top col-md-12">
      <div class="container">
        <%= link_to root_path, class: "navbar-brand col-md-3", id: "" do %>
          <!--<h2 id="brandname">Lunchize<img src="http://www.unc.edu/~jphuss/COMP101/lab16/dice.png" height="38" width="38"><span id="second"><span></span></span></h2>-->
          <h2 id="brandname">Lunchise<span id="second"><span></span></span></h2>
        <% end %>
        <div class="col-md-8 pull-right">
            <ul class="nav navbar-nav navbar-right" id="navbar-list">
              <% if current_chef %>
                <li><%= link_to "My detials", edit_chef_registration_path  %></li>
                <li><%= link_to "My meals", meals_path  %></li>
                <li class="logout pull-right">
                  <%= link_to('Logout', destroy_chef_session_path,
                  class: 'btn btn-xs btn-danger logout-btn', title: 'Logout', :method => :delete) %>
                </li>
              <% elsif current_customer %>
                <li class="counter"><p id="counter"><%= current_customer.customer_meals.count %></p><span>My Meals</span></li>
                <li class="dropdown tabs tab1">
                  <a href="#" id="tab1link" class="dropdown-toggle"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <!--<p id="user"><%#= current_customer.email[0..5] %> <span class="caret"></span></p>-->
                    <p  class="balance" >£12.45</p>
                    <p id="user">My Balance <span class="caret"></span></p>
                  </a>
                  <ul class="dropdown-menu" id="login-list">
                                        <!--<p id="user"><%#= current_customer.email[0..5] %> <span class="caret"></span></p>-->
                    <li><a>Top-up</a></li>
                    <li><%= link_to "Edit setting", edit_customer_registration_path  %></li>
                    <li role="separator" class="divider"></li>
                    <!--<li><a><%#= current_customer.email[0..12] %>...</a> </li>-->

                    <li><%= link_to "#{current_customer.email[0..6]}... Log Out", destroy_customer_session_path, :method => :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li class="dropdown">
                  <a href="#" id="login" class="dropdown-toggle tabs" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login <span class="caret"></span></a>
                  <ul class="dropdown-menu" id="login-list">
                    <li><%= link_to 'Customer Login', new_customer_session_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to 'Chef Login', new_chef_session_path %></li>
                    <li><%= link_to 'Chef Registration', new_chef_registration_path %></li>
                    <li><%= link_to 'Customer Registration', new_customer_registration_path %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 main">
          <div id="bootstrap-flash">
            <%= bootstrap_flash %>
          </div>
          <%= yield %>
        </div>
        
        
      </div><!--/row-->
      <footer>
        <p>&copy; Panzfree 2017 | Contact | How It Works | Terms | Chefs | FAQs</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>